# -*- coding: utf-8 -*-
"""modoul_penjumlah.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19B3cbGq3mF1xqeqOQmQPQeGLjbs_uKoS
"""

def penjumlahan (angka_1, angka_2):
  jumlah = angka_1 + angka_2
  return jumlah